### ISSUE TITLE
output_labels.txt; No such file or directory

### ISSUE THREAD

**Issue by alexluleme** [wisdal/image-classification-transfer-learning#3]
Where does this output_labels.txt come from; or where is located?

**Comment by PrakharPrashantSingh** [comment]
i am also facing same error!

**Comment by wisdal** [comment]
Check out lines 1172-1177 of the retrain script.

**Comment by PrakharPrashantSingh** [comment]
according to the script, it must be in C:/tmp folder, but nothing is in there except inception model that code downloaded!
please help in this context
Thanks

**Comment by wisdal** [comment]
Not sure if you checked those lines -When calling the retrain script, you are expected to pass an **output_labels** argument. By default, it is set to **/tmp/output_labels.txt**. If I used **C:/tmp/output_labels.txt** in the test notebook, it is because this is what I set --output_labels to during retraining.

**Comment by PrakharPrashantSingh** [comment]
i don't know i was trying something (basically experimenting) and resolved this error, okay what i did is i passed retained labels and retrained.pb in place of output_labels.txt and .pb, the program moved forward, but this time it is saying: FileNotFoundError: [Errno 2] No such file or directory: '.\\test_img2\\test_1000a.jpg' and one more thing i need to tell you is, while running preprocess.ipynb i left the last block, as it was giving some error, i think that's why training set is not properly created!

**Comment by PrakharPrashantSingh** [comment]
Thanks Man for this code, i ran it successfully and classified your test set! now i this was just checking whether your code is running or not.... now i need to create a algorithm for classifying my fruit data!

But Thanks for Your help!

**Comment by wisdal** [comment]
Wish you luck!
